/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException, InterruptedException {
        String host = args[0];
        String port = args[1];
        Client client = new Client(host, Integer.parseInt(port));
        while(true) {
            client.makePingRequest();
            Thread.sleep(1000);
        }
    }
}
